dent/urls.py
from django.urls import path
from . import views

app_name = 'dent'
urlpatterns = [
    path('',views.home, name = 'home'),
    path('searchid/',views.searchid, name = 'searchid'),
    path('userpatientreg/', views.userpatientregview, name = 'userpatientreg'),
    path('staffreg/',views.staffregview, name = 'staffreg'),
    path('login/', views.loginpage, name= 'login'),
    path('logout/', views.logoutpage, name= 'logout'),
    path('list/', views.listview, name = 'listo'),
    path('logpatient/<int:pk>', views.logpatientview, name = 'logpatient'),
    path('logpatientappointment/<int:pk>', views.logpatientappointmentview, name = 'logpatientappointment'),
    path('warning',views.warningview, name = 'warning'),
    path('staffprofile/<int:pk>',views.staffprofileview, name = 'staffprofile'),
    path('<int:pk>/',views.detail, name = 'detail'),
    path('staffdetail/<int:pk>',views.staffdetailview, name = 'staffdetail'),
    path('unlogpatient/', views.unlogpatientview, name= 'unlogpatient'),
    path('appointment/<int:pk>', views.appointmentview, name= 'appointment'),
    path('updateregview/<int:pk>', views.updateregview, name= 'updateregview'),
    path('registration/<int:pk>/delete', views.DeleteRegistrationView.as_view(), name = 'deleteregistration'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',TemplateView.as_view(template_name = 'dent/home.html')),
    path('', include('dent.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dent/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.conf import settings
import string
import random


class Staff(models.Model):
    TITLES = (
        ('Dr', 'Dr'),
        ('MDDr', 'MDDr'),
        ('MUDr', 'MUDr'),
        ('Bc','Bc'),
        ('Mrs', 'Mrs'),
        ('Mr', 'Mr'),
    )
    FIELDS = (
        ('Dental Surgery', 'Dental Surgery'),
        ('Stomatology', 'Stomatology'),
        ('Implantology', 'Implantology'),
        ('Dental Hygiene', 'Dental Hygiene'),
        ('Administrator','Administrator'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=20, choices = TITLES)
    fname = models.CharField(max_length = 100)
    sname = models.CharField(max_length= 100)
    about = models.TextField(null= True, blank = True)
    profile_pic = models.ImageField(null = True, blank= True)
    field = models.CharField(max_length=250, choices = FIELDS, default=000)
    
    def __str__(self):
        return self.sname


class Meta:
    db_table = 'Patient`s data'

class Patient(models.Model):
    COMPANIES = (
        ('GHI', 'GHI'),
        ('Confidence', 'Confidence'),
        ('Union', 'Union'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, null= True, blank = True)
    fname = models.CharField(max_length=100)
    sname = models.CharField(max_length=100)
    insurance_c = models.CharField(max_length=20,choices=COMPANIES)
    cell_phone_num = models.IntegerField()
    email = models.EmailField(max_length= 254, null = True, blank= True) 
    def __str__(self):
        return self.fname
        

class Appointment(models.Model):
    patient = models.ForeignKey('Patient', on_delete= models.CASCADE)
    doctor = models.ForeignKey('Staff', on_delete = models.CASCADE)
    key = models.CharField(max_length = 15, null = True)
    date = models.DateField(auto_now_add= False)
    time = models.TimeField(auto_now_add=False)
    notes = models.TextField(null=True, blank = True)



#### CHECK FOR EXISTING APPOINTMENT FOR THE GIVEN DOCTOR, DATE, TIME ####
def appointmentcheck():
    new_appointment = Appointment.objects.last()
    n = 0
    dict_new_appointment = {
        'doctor': new_appointment.doctor.id,
        'date': new_appointment.date,
        'time': new_appointment.time}
    for appoint in Appointment.objects.values('doctor','date','time'):
        if dict_new_appointment == appoint:
            n += 1
    if n >= 2:
        new_appointment.delete()
        return redirect('dent:warning')
    else: 
        return redirect('dent:detail', new_appointment.id )


def keygen(length = 10, code = string.ascii_uppercase + string.digits):
    key = ''.join(random.choice(code) for _ in range(length))
    return key


def sendemail(request, appointment):
    if request.method =="POST":
        if appointment.patient.email:
            subject = "Hello from 987dent"
            message = f"Your registration key is = {appointment.key}"
            send_mail(
                subject,
                message,
                settings.EMAIL_HOST_USER,
                [appointment.patient.email],
                fail_silently= False,
            )
            msg = f'The email with appointment details was sent to: {appointment.patient.email}'
            return msg

    

dent/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views import View
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm ### Login form
from django.core import exceptions
from django import forms
from django.forms import inlineformset_factory

from dent.decorators import unauthenticated_user

from .models import Patient, Staff, Appointment, appointmentcheck, keygen, sendemail
from .forms import AppointmentForm, CreateUserForm, PatientForm, StaffForm, HOUR_CHOICES
from .filters import filter
from .decorators import unauthenticated_user, allowed_users

from datetime import datetime


#### HOME PAGE ####
def home(request):
    doctors = Staff.objects.filter(id__range = (2,10))
    id = Staff.objects.filter(id__range = (2,10)).values('id')
    context = {
        'form':doctors,
        'id':id}
    return render(request, 'dent/home.html', context)


#### LOG PATIENT ####
@login_required(login_url = 'dent:login')
@allowed_users(allowed_roles = ['patients'])
def logpatientview(request,pk):
    ''' 
    try refers to that logpatient can update his personal info
    except enables newly logged-in patient to pass in his/her required personal info
        - it takes some personal info from the User`s database table  
    '''
    try:
        current_patient = request.user.patient
        update_patientform = PatientForm(instance = current_patient)
        if request.method == "POST":
            update_patientform = PatientForm(request.POST, instance = current_patient)
            if update_patientform.is_valid():
                update_patientform.save()
                return redirect('dent:logpatientappointment', pk = request.user.patient.id )
        
        ctx = {'patientform':update_patientform}
        return render(request, 'dent/logpatient.html', ctx)

    except:
        saveduser = User.objects.get(id = pk)
        patientform = PatientForm(initial={
            'user':saveduser,
            'fname':saveduser.first_name,
            'sname':saveduser.last_name,
            'email':saveduser.email})
        if request.method == 'POST':
            patientform = PatientForm(request.POST,
            initial={
                'fname':saveduser.first_name,
                'sname':saveduser.last_name,
                'email':saveduser.email,})
            if patientform.is_valid():
                patientform.save()
                new_patient = Patient.objects.last()
                return redirect('dent:logpatientappointment', pk =  new_patient.id )

        ctx = {'patientform':patientform, }
        return render(request, 'dent/logpatient.html', ctx)


@login_required(login_url='dent:login')
@allowed_users(allowed_roles = ['patients'])
def logpatientappointmentview(request,pk):
    ''' 
    try:
        - make an appointment of loged in patient, 
        - check the appointment by appointmentcheck(),
        - throw in the appointment/appointments from database of current loged-in patient
    except redirects the newly logged-in user to logpatient view in order to pass in his/her required personal info  
    '''
    try:
        logpatient = Patient.objects.get(id = pk)
        key = keygen()
        PatientFormSet = inlineformset_factory(
            Patient, Appointment, 
            fields = ('patient','doctor', 'date', 'time','notes','key'),
            extra = 1,
            widgets = {
                'doctor':forms.Select(attrs = {'class':'text-input'}),
                'date':forms.DateInput(attrs = {'type':'date', 'class':'text-input'}),
                'time':forms.Select(
                    attrs = {'class':'text-input'},
                    choices = HOUR_CHOICES),
                'notes':forms.Textarea(attrs = {'class':'textarea-input'}),
                'key':forms.TextInput(attrs = {'class':'text-input', 'value': key, "type":"hidden"})},
            can_delete=False)
        filter_list = filter(request,appointments = Appointment.objects.exclude(date__lt = datetime.today()))
        formset = PatientFormSet(instance = logpatient, queryset = Appointment.objects.none())
        if request.method == "POST":
            formset = PatientFormSet(request.POST, instance = logpatient)
            if formset.is_valid():
                formset.save()
                return appointmentcheck()

        if Appointment.objects.filter(patient = logpatient.id).exists():
            if Appointment.objects.filter(patient = logpatient.id).count() > 1:
                patientappoints = Appointment.objects.filter(patient = logpatient.id)
                ctx = {
                    'appointments':filter_list[2],
                    'appointfilter':filter_list[1],
                    'patientappoints':patientappoints,
                    'formset':formset,
                    'logpatient':logpatient}
                return render(request, 'dent/logpatientappointment.html', ctx)

            if Appointment.objects.filter(patient = logpatient.id).count() == 1:
                patientappoint = Appointment.objects.get(patient = logpatient.id)
                ctx = {
                    'appointments':filter_list[2],
                    'appointfilter':filter_list[1],
                    'patientappoint':patientappoint,
                    'formset': formset,
                    'logpatient':logpatient}
                return render(request, 'dent/logpatientappointment.html', ctx)

        ctx = {
            'appointments':filter_list[2],
            'appointfilter':filter_list[1],
            'formset': formset,
            'logpatient':logpatient}
        return render(request, 'dent/logpatientappointment.html', ctx)

    except exceptions.ObjectDoesNotExist:
            return redirect('dent:logpatient', pk = request.user.id)
                

def warningview(request):
    '''Used in both cases, when logged-in patient or not registrated patient try to make an appointment '''
    msg = 'Sorry, but your appointment collides with another appointment and therefore must be deleted'
    ctx= {'msg':msg}
    return render(request, 'dent/warning.html', ctx)
            

#### STAFF ####
@login_required(login_url='dent:login')
@allowed_users(allowed_roles = ['staff'])
def staffprofileview(request,pk): 
    try:
        current_staff = request.user.staff
        update_profile_form = StaffForm(instance = current_staff)
        if request.method == "POST":
            update_profile_form = StaffForm(request.POST, request.FILES, instance = current_staff)
            if update_profile_form.is_valid():
                update_profile_form.save()
                return redirect('dent:staffdetail', pk = request.user.staff.id )
        
        ctx = {'profileform':update_profile_form}
        return render(request, 'dent/staffprofile.html', ctx)

    except:
        profileform = StaffForm()
        if request.method == 'POST':
            profileform = StaffForm(request.POST,request.FILES)
            if profileform.is_valid():
                profileform.save()
                new_doctor_name = profileform.cleaned_data.get('sname')
                new_doctor = Staff.objects.get(sname = new_doctor_name)
                return redirect('dent:staffdetail', pk =  new_doctor.id )

        ctx = {
            'profileform':profileform,
        }
        return render(request, 'dent/staffprofile.html', ctx)


def staffdetailview(request,pk):
    '''
    try points to doctor/nurse detailed view if the profile is filled
    '''
    try: 
        employee = Staff.objects.get(id = pk)
        ctx = {'employee':employee}
        return render(request, 'dent/staffdetail.html',ctx)

    except exceptions.ObjectDoesNotExist:
        try:
            return redirect('dent:staffdetail',pk = request.user.staff.id)

        except:
            return redirect('dent:staffprofile',pk =request.user.id )

#### LIST OF APPOINTMENTS ####
@login_required(login_url='dent:login')
@allowed_users(allowed_roles = ['staff'])
def listview(request):
    ''' 
    List of appointments created only for staff
        -contains patients personal info too
        -can be filtred by patient`s last name, given doctor or appointment date
    '''
    filter_list = filter(request,appointments = Appointment.objects.all())
    ctx = {
        'appointments':filter_list[2],
        'appointfilter':filter_list[1]}
    return render(request, 'dent/listview.html', ctx)


###### UNLOG PATIENT ######
def unlogpatientview(request):
    ''' View for filling personal info '''
    patientform = PatientForm()
    if request.method == 'POST':
        patientform = PatientForm(request.POST) 
        if patientform.is_valid():
            patientform.save()
            new_patient = Patient.objects.last()
            return redirect('dent:appointment', pk = new_patient.id)

    context = {'patientform':patientform}
    return render(request, 'dent/unlogpatient.html',context)


def appointmentview(request,pk):
    ''' Appointment of patient without registration '''
    unlogpatient = Patient.objects.get(id = pk)
    patientform = PatientForm(instance = unlogpatient)
    key = keygen()
    appointform = AppointmentForm(initial = {'key':key, 'patient':unlogpatient})
    filter_list = filter(request,appointments = Appointment.objects.exclude(date__lt = datetime.today()))
    if request.method == 'POST':
        appointform = AppointmentForm(request.POST)
        if appointform.is_valid():
            appointform.save()
            return appointmentcheck()

    context = {
            'appointments':filter_list[2],
            'appointfilter':filter_list[1],
            'patientform':patientform,
            'appointform':appointform}

templates/dent/deleteregister.html
{% extends 'dent/main.html' %}
{% block content %}
<div class="container container-relative">
    <p> Are you sure to delete your appointment with {{ deleteform.id }} id ?</p>
    <form method = 'post' action = ''>
        {% csrf_token %}
        <input type = 'submit' value = 'Delete' class="delete">
        <a href = "{{ request.META.HTTP_REFERER }}"><button type = 'button' class="return">Return</button></a>
    </form>
</div>
{% endblock %}

templates/dent/detail.html
{% extends 'dent/main.html' %}
{% block content %}
<div class="container container-relative">
    <h3> Registration key of your appointment: {{ appointment.key }}</h3>
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}
    {% if appointment.patient.email %}
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="submit">
                Send me the appointment details on: {{ appointment.patient.email }}
            </button>
        </form>
    {% endif %}
    <ul>
        <li> First name: {{ appointment.patient.fname }}</li>
        <li> Last name: {{ appointment.patient.sname }}</li>
        <li> Insurance company: {{ appointment.patient.insurance_c }}</li>
        <li> Email: {{ appointment.patient.email }}</li>
        <li> Doctor: {{ appointment.doctor }}</li>
        <li> Date: {{ appointment.date }}</li>
        <li> Time: {{ appointment.time }}</li>
        <li> Extra notes: {{ appointment.notes }}</li>
    </ul>
    <a href = "{% url 'dent:updateregview' appointment.id %}"><button type = 'button' class="submit">Update</button></a>
    <a href = "{% url 'dent:deleteregistration' appointment.id %}"><button type = 'button' class="delete">Delete</button></a>
    {% if request.user.is_staff %}
        <a href = "{{ request.META.HTTP_REFERER }}"><button type = 'button' class="return">Return</button></a>
    {% endif %}
</div>
{% endblock %}

templates/dent/home.html
{% extends 'dent/main.html' %}
{% load static %}
{% block content%}
<div class = 'Mcontainer'>
    <div class = "top-item">
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% endif %}
        <h2> For your helthier smile </h2>
    </div>
    <div class = "middle-item">
        <h2 class ='headline2'>Team</h2>
        <form method = 'get' class="doctors">
            {% for doc in form %}
                <div class="doctor">
                    <h4>{{ doc.field }}: {{ doc.title }}. {{ doc.fname }} {{ doc.sname }}</h4>
                        {% if doc.profile_pic %}
                            <a href ="{% url 'dent:staffdetail' doc.id %}">
                                <img src = "{{ doc.profile_pic.url }}" height="400" width = '400'>
                            </a>
                        {% else %}
                            <img src= "{% static 'images/doktor_default.png' %}" height="400" width = '400'>
                        {% endif %}
                    <br>
                    <a href ="{% url 'dent:staffdetail' doc.id %}"><button type = 'button' class="submit submit-width">Profile</button></a>
                </div>
        {% endfor %}
        </form>
    </div>
    <div class = "bottom-item">
        <strong>Photo Gallery</strong>
    </div>
</div>
            

{% endblock %}

templates/dent/listview.html
{% extends 'dent/main.html' %}
{% block content %}
<h2 class = "headline2">List of Patients</h2>
{% if appointments %}
<form method = 'GET' class="filter">
    Last name:{{ appointfilter.form.patient }}
    Date:{{ appointfilter.form.date }}
    Doctor:{{ appointfilter.form.doctor_char }}
    <button type ='submit' class="submit paddmarg0">Search</button>
    <button type="button" class="return paddmarg0" onclick="ClearFields();">Clear</button>
</form>
<table class= "patients_table">
    <tr class="first_row">
        <th>First name</th>
        <th>Last name</th>
        <th>Phone number</th>
        <th>email</th>
        <th>Date</th>
        <th>Time</th>
        <th>Doctor </th>
        <th>Detail</th> 
    </tr>         
    {% for appointment in appointments %}
        <tr>
            <td>{{ appointment.patient.fname }}</td>
            <td>{{ appointment.patient.sname }}</td>
            <td>{{ appointment.patient.cell_phone_num }}</td>
            <td>{{ appointment.patient.email }}</td>
            <td>{{ appointment.date }}</td>
            <td>{{ appointment.time }}</td>
            <td>{{ appointment.doctor }}</td> 
            <td><a href = "{% url 'dent:detail' appointment.id %}">Detail</a></td>  
        </tr>
    {% endfor %}   
</table>
{% else %}
<form method = 'GET' class="filter">
    Last name:{{ appointfilter.form.patient }}
    Date:{{ appointfilter.form.date }}
    Doctor:{{ appointfilter.form.doctor_char }}
    <button type ='submit' class="submit paddmarg0">Search</button>
    <button type="button" class="return paddmarg0" onclick="ClearFields();">Clear</button>
</form>
<table class= "patients_table">
    <tr class="first_row">
        <th>First name</th>
        <th>Last name</th>
        <th>Phone number</th>
        <th>email</th>
        <th>Date</th>
        <th>Time</th>
        <th>Doctor </th>
        <th>Detail</th> 
    </tr>  
</table>
{% endif %}
{% endblock %}

templates/dent/login.html
{% extends 'dent/main.html' %}
{% load static %}
{% block content %}

<div class="container container-middle">
	<h2>Log in</h2>
	<form method="POST" action="">
		{% csrf_token %}
	
		<input type="text" name="username" placeholder="Username..." class="text-input">
		<input type="password" name="password" placeholder="Password..." class="text-input" >
		<input class="submit" type="submit" value="Log in">
			
	</form>
	Don't have an account? <a href="{% url 'dent:userpatientreg' %}"><button type="button" class="return">Sign Up</button></a>
	{% for message in messages %}
		<p id = 'messages'>{{ message }}</p>
	{% endfor %}
</div>
{% endblock %}

templates/dent/logpatient.html
{% extends 'dent/main.html' %}
{% load static %}
{% block content %}

<div class="container container-middle">
    <h2> Patient {{ request.user }}</h2>
    <form method = "POST" action = "">
        {% csrf_token %}
        <p hidden>{{ patientform.user }} </p>

        <label for="fname">First name</label>
        {{ patientform.fname }}
    
        <label for="sname">Last Name</label>
        {{ patientform.sname }}

        <label for="insurance_c">Insurance</label>
        {{ patientform.insurance_c }}

        <label for="cell_phone_num">Phone number</label>
        {{ patientform.cell_phone_num }}

        <label for="email">Email</label>
        {{ patientform.email }}

        <button class="submit" type = 'submit'>Submit</button>
    </form>
</div>

{% endblock %}

templates/dent/logpatientappointment.html
{% extends 'dent/main.html' %}
{% load static %}
{% block content %}
<div class ='appoint-container'>
    <div class = 'appoint-item1'>
        <div class="header-of-card">
            <h2> Patient {{ request.user }}</h2>
        </div>
        <div class="card-item">
            Name:{{ logpatient.fname }} {{ logpatient.sname }}
        </div>
        <div class="card-item">
            Insurance:{{ logpatient.insurance_c }}
        </div>
        <div class="card-item">
            Phone number:{{ logpatient.cell_phone_num }}
        </div>
        <div class="card-item">
            Email:{{ logpatient.email }}
        </div>
        <div>
            <a href = "{% url 'dent:logpatient' request.user.patient.id %}"><button type='button' class="submit">Update</button></a>
        </div>
        <h2 class="h2-margin-top">{{ logpatient.fname }}`s appointments</h2>
        <table class="patients_table">
            <tr>
                <th>Doctor</th>
                <th>Date</th>
                <th>Time</th>
                <th>Detail</th>
            </tr>
            {% if patientappoints %}
                {% for appoint in patientappoints %}
                    <tr>
                        <td>{{ appoint.doctor }}</td>
                        <td>{{ appoint.date }}</td>
                        <td>{{ appoint.time }} </td>
                        <td><a href = "{% url 'dent:detail' appoint.id %}">Detail</a></td>
                    </tr>
                {% endfor %}
            {% endif %}
            {% if patientappoint %}
            <tr>
                <td>{{ patientappoint.doctor }}</td>
                <td>{{ patientappoint.date }}</td>
                <td>{{ patientappoint.time }} </td>
                <td><a href = "{% url 'dent:detail' patientappoint.id %}">Detail</a></td>
            </tr>
            {% endif %}
        </table>
    </div>
    <div class = 'appoint-item3 container container-relative'>
        <h2>Appointment form</h2>
        <form method = "POST" action = "">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for form in formset %}
                {{ form }}
                <button class="submit" type = 'submit'>Submit</button>
            {% endfor %}
        </form>
    </div>
    <div class = 'appoint-item2 container container-relative'>
        <h2>Appointments filter</h2>
        <form method = 'GET'>
            <label for="id_doctor">Doctor</label>
            {{ appointfilter.form.doctor }}
            <label for="exact-date">Date</label>
            {{ appointfilter.form.exact_date }}
            <button type ="submit" class="submit">Search</button>
        </form>
        <table>
            <tr>
                <th>Doctor</th>
                <th>Date</th>
                <th>Time</th>
            </tr>
            {% for appointment in appointments %}
            <tr>
                <td>{{ appointment.doctor }}</td> 
                <td>{{ appointment.date }}</td>
                <td>{{ appointment.time }}</td>  
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

templates/dent/search.html
{% extends 'dent/main.html' %}
{% block content %}
    <center>
    <h2>{{ a }} registration key = {{ searched_key }}.</h2>
    <a href ="{% url 'dent:home' %}">Go to the home page</a>
    </center>

{% endblock %}

templates/dent/staffdetail.html
{% extends 'dent/main.html' %}
{% load static %}
{% block content %}
<div class="detail">
    <h2 class="detail-item1"> {{ employee.title }}.{{ employee.fname }} {{ employee.sname }}</h2>
    <img src = "{{ employee.profile_pic.url }}" width ="450" height = "450" class="detail-item2">
    <div class="detail-item3">{{ employee.about }}</div>
    {% if request.user.is_staff  %}
        <a class="detail-item4" href = "{% url 'dent:staffprofile' employee.id %}"><button type = 'button' class="submit" >Update</button></a>
    {% endif %}
</div>

{% endblock %}

templates/dent/staffprofile.html
{% extends 'dent/main.html' %}
{% load static %}
{% block content %}
<div class="container container-middle">
    <form method="POST" action="" id = 'staffform' enctype="multipart/form-data">
        {% csrf_token %}
        <div hidden>
            <p><strong> User </strong></p>
            <input type = 'text' name = 'user' value = '{{ user.id }}' readonly>
        </div>
        <div>
            Title {{ profileform.title }} 
        </div>
        <div>
            Firts name {{ profileform.fname }}
        </div>
        <div>
            Last name {{ profileform.sname }} 
        </div> 
        <div>
            {% if request.user.staff.profile_pic %}
                {{ profileform.profile_pic }}
                <img class="profile-pic" src="{{ request.user.staff.profile_pic.url }}" width ="350" height = "350">
            {% else %}
                {{ profileform.profile_pic }}
                <img class="profile-pic" src="{% static 'images/doktor_default.png' %}" width ="350" height = "350">
            {% endif %} 
        </div>
        <div>
            Field {{ profileform.field }}
        </div>
        <div>
            About {{ profileform.about }} 
        </div>
        <input type="submit" value = 'Register' class="submit">
    </form>
</div>
{% endblock %}

templates/dent/unlogappointment.html
{% extends 'dent/main.html' %}
{% block content %}
<h2>Create an Appointment</h2>
<div class="container container-left container-opacity">
    <h2> Personal Information </h2>
    <form method = 'post' action = ''>
        {% csrf_token %}

        <label for="fname">First name</label>
        {{ patientform.fname }}

        <label for="sname">Last name</label>
        {{ patientform.sname }}

        <label for="insurance_c">Insurance</label>
        {{ patientform.insurance_c }}

        <label for="cell_phone_num">Phone number</label>
        {{ patientform.cell_phone_num}}

        <label for="email">Email</label>
        {{ patientform.email }}
      
    </form>
</div>
<div class="container container-right">
    <h2> Appointment form </h2>
    <form method = 'post' action = ''>
        {% csrf_token %}
        
        <p hidden>{{ appointform.patient }}</p>

        <label for="doctor">Doctor</label>
        {{ appointform.doctor }}

        <label for="date">Date</label>
        {{ appointform.date }}

        <label for="time">Time</label>
        {{ appointform.time }}

        <label for="notes">Notes</label>
        {{ appointform.notes }}

        <label hidden for="key">Registration Key</label>
        {{ appointform.key }}

        <button class="submit" type = 'submit'>Submit</button>
        <a href = "{% url 'dent:unlogpatient' %}">
            <button type = 'button' class="return">Back</button>
        </a>
    </form>
</div>
<div class = 'container container-middle'>
    <h2> Filter of current appointments </h2>
    <form method = 'GET'>
        <label for="doctor">Doctor</label>
        {{ appointfilter.form.doctor }}
        <label for="exact-date">Date</label>
        {{ appointfilter.form.exact_date }}
        <button type ="submit" class="submit">Search</button>
    </form>
    <table>
        <tr>
            <th>Doctor</th>
            <th>Date</th>
            <th>Time</th>
        </tr>
        {% for appointment in appointments %}
        <tr>
            <td>{{ appointment.doctor }}</td> 
            <td>{{ appointment.date }}</td>
            <td>{{ appointment.time }}</td>  
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/dent/updateregview.html
{% extends 'dent/main.html' %}
{% load static %}
{% block content %}
<div class="container container-middle">
    <form method = 'POST' action = "">
        {% csrf_token %}
        <div hidden>
            {{ updatepatform.user }}
        </div>
        First name {{ updatepatform.fname }}
        Last name {{ updatepatform.sname }}
        Insurance {{ updatepatform.insurance_c }}
        Phone number {{ updatepatform.cell_phone_num }}
        Email {{ updatepatform.email }}
        <div hidden>
            {{ updateappform.patient}}
        </div>
        Doctor {{ updateappform.doctor }}
        Date {{ updateappform.date}}
        Time {{ updateappform.time }}
        Notes {{ updateappform.notes }}
        <div hidden>
            {{ updateappform.key}}
        </div>
        <input type = 'submit' value = 'Update' class="submit">
        <input type = 'button' class="return"
                onclick="location.href='http://127.0.0.1:8000/'; return false;"
                value = 'Escape'>
    </form>
</div>
{% endblock %}
        
        
        
        
       
        
        
        
            
        
            
        

templates/dent/warning.html
{% extends 'dent/main.html' %}
{% block content %}
<h2> {{ msg }}</h2>
    {% if request.user.patient.id %}
        <a href="{% url 'dent:logpatientappointment' request.user.patient.id  %}">Please, filter out the table with current appointments and try it again</a>
    {% else %}
        <a href="{% url 'dent:unlogpatient' %}">Please, filter out the table with current appointments and try it again</a>
    {% endif %}
{% endblock %}